version: '3'

services:
  magicmirror:
    image: bastilimbach/docker-magicmirror
    container_name: magicmirror
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/iac/applications/magic-mirror/config:/opt/magic_mirror/config
      - ~/magic_mirror/modules:/opt/magic_mirror/modules
    ports:
      - 8888:8080
