# https://taskfile.dev

version: '3'

silent: true

tasks:

  default:
    desc: Run complete configuration for this host.
    cmds:
      - task: configure-inital
      - task: hardware
      - task: configure-disk-management
      - task: configure-backup
      - task: configure-applications # Might automatically reboot the host
      - echo "No applications are 'up'ed by default to prevent migration issues"

  app:up:
    desc: Start application APP (e.g. APP=web task app:up)
    dir: applications/{{.APP}}
    cmds:
      - docker-compose -p {{.APP}} -f {{.APP}}-compose.yml up -d

  app:down:
    desc: Stop application APP (e.g. APP=web task app:down)
    dir: applications/{{.APP}}
    cmds:
      - docker-compose -p {{.APP}} -f {{.APP}}-compose.yml down


  configure-applications:
    desc: Configure applications for/on this host
    dir: applications
    cmds:
      - |
        if [ -f "$(hostname).sh" ]; then
          ./$(hostname).sh
        fi
      - echo "No applications are 'up'ed by default to prevent migration issues"

  configure-backup:
    desc: Configure backup
    dir: backup
    cmds:
      - |
        if [ -f "$(hostname).sh" ]; then
          ./$(hostname).sh
        fi

  configure-disk-management:
    desc: Configure disks, mounts, filesystems
    dir: disk-management
    cmds:
      - |
        if [ -f "$(hostname).sh" ]; then
          ./$(hostname).sh
        fi

  configure-initial:
    desc: Configure hostname, os
    dir: initial
    cmds:
      - |
        if [ -f "$(hostname).sh" ]; then
          ./$(hostname).sh
        fi

  configure-hardware:
    desc: Configure hardware
    dir: hardware
    cmds:
      - |
        if [ -f "$(hostname).sh" ]; then
          ./$(hostname).sh
        fi

  transcrypt:init:
    desc: Initiliaze the repos with transcrypt
    cmds:
      - |
        transcrypt -c aes-256-cbc
