version: "3.8"

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - mariadb.secret.ignored
    ports:
    - 3306:3306
    volumes:
    - /mnt/volume/mariadb:/var/lib/mysql
