version: "3.8"

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
    - /mnt/volume/caddy:/data
    networks:
    - shared

networks:
  shared:
    external:
      name: shared
