version: "3.8"

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ~/iac/applications/web/Caddyfile:/etc/caddy/Caddyfile
    - /mnt/volume/caddy:/data # for persistent certificates
    - ~/thetillhoff.de/output:/var/www/html
    networks:
    - shared

networks:
  shared:
    external:
      name: shared
