version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: always
    env_file:
      - ~/iac/applications/vaultwarden/vaultwarden.secret.ignored
    environment:
      - DOMAIN=https://pw.enforge.de
      - SIGNUPS_ALLOWED=false
    volumes:
    - /mnt/volume/vaultwarden:/data
    networks:
    - shared

networks:
  shared:
    external:
      name: shared
