version: "3.8"

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: always
    env_file:
      - bitwarden.secret.ignored
    environment:
      - DOMAIN=https://pw.enforge.de
      - SIGNUPS_ALLOWED=false
    volumes:
    - /mnt/volume/bitwarden:/data
    networks:
    - shared

networks:
  shared:
    external:
      name: shared
